theme = "hugo-book"
baseURL = 'https://enchanting-dieffenbachia-b57d92.netlify.app/'
languageCode = 'en-us'
title = 'My New Hugo Site'
[build]
command = "hugo --gc --minify -D"
publish = "public"

[context.production.environment]
HUGO_VERSION = "0.147.5_extended"          # 普通版本
# HUGO_VERSION = "0.147.5_extended" # 扩展版本（如需）